const translations: Record<string, string> = {
  "Start Event": "开始事件",
  "End Event": "结束事件",
  Task: "任务",
  "User Task": "用户任务",
  "Service Task": "服务任务",
  "Script Task": "脚本任务",
  "Manual Task": "手动任务",
  "Send Task": "发送任务",
  "Receive Task": "接收任务",
  "Business Rule Task": "业务规则任务",
  "Exclusive Gateway": "排他网关",
  "Parallel Gateway": "并行网关",
  "Inclusive Gateway": "包容网关",
  "Event based Gateway": "事件网关",
  "Intermediate Throw Event": "中间抛出事件",
  "Intermediate Catch Event": "中间捕获事件",
  "Message Start Event": "消息开始事件",
  "Timer Start Event": "定时开始事件",
  "Message End Event": "消息结束事件",
  Delete: "删除",
  Remove: "移除",
  "Append Task": "追加任务",
  "Append EndEvent": "追加结束事件",
  "Create Task": "创建任务",
  "Create StartEvent": "创建开始事件",
  "Create EndEvent": "创建结束事件",
  "Change type": "更改类型",
  "Connect using Sequence/MessageFlow or Association":
    "使用顺序流/消息流/关联进行连线",
  "Create DataObjectReference": "创建数据对象引用",
  "Create DataStoreReference": "创建数据存储引用",
  "Search in diagram": "在图中搜索",
  "Open minimap": "打开缩略图",
  "Activate hand tool": "启用手形工具",
  "Activate lasso tool": "启用套索工具",
  "Activate create/remove space tool": "启用创建/移除间距工具",
  "Activate global connect tool": "启用全局连线工具",
  "Create start event": "创建开始事件",
  "Create intermediate/boundary event": "创建中间/边界事件",
  "Create end event": "创建结束事件",
  "Create gateway": "创建网关",
  "Create task": "创建任务",
  "Create data object reference": "创建数据对象引用",
  "Create data store reference": "创建数据存储引用",
  "Create expanded sub-process": "创建展开子流程",
  "Create pool/participant": "创建泳池/参与者",
  "Create group": "创建分组",
  "Append end event": "追加结束事件",
  "Append gateway": "追加网关",
  "Append task": "追加任务",
  "Append intermediate/boundary event": "追加中间/边界事件",
  "Intermediate throw event": "中间抛出事件",
  "End event": "结束事件",
  "Message start event": "消息开始事件",
  "Timer start event": "定时开始事件",
  "Conditional start event": "条件开始事件",
  "Signal start event": "信号开始事件",
  "Change element": "更改元素",
  "Add text annotation": "添加文本注释",
  "Connect to other element": "连接到其他元素",
  "Parallel gateway": "并行网关",
  "Inclusive gateway": "包容网关",
  "Complex gateway": "复杂网关",
  "Event-based gateway": "事件网关",
  "Data store reference": "数据存储引用",
  Collection: "集合",
  "Connect using data input association": "使用数据输入关联连接",
  "Data object reference": "数据对象引用",
  "Add lane above": "在上方添加泳道",
  "Divide into two lanes": "拆分为两条泳道",
  "Divide into three lanes": "拆分为三条泳道",
  "Add lane below": "在下方添加泳道",
  "Empty pool/participant (removes content)": "清空泳池/参与者（移除内容）",
  "Participant multiplicity": "参与者多重性",
  Transaction: "事务",
  "Event sub-process": "事件子流程",
  "Ad-hoc sub-process": "临时子流程",
  "Sub-process (collapsed)": "子流程（折叠）",
  "Parallel multi-instance": "并行多实例",
  "Sequential multi-instance": "顺序多实例",
  Loop: "循环",
  "User task": "用户任务",
  "Service task": "服务任务",
  "Send task": "发送任务",
  "Receive task": "接收任务",
  "Manual task": "手动任务",
  "Business rule task": "业务规则任务",
  "Script task": "脚本任务",
  "Call activity": "调用活动",
  "Call Activity": "调用活动",
  "Sub-process (expanded)": "子流程（展开）",
  "Ad-hoc sub-process (collapsed)": "临时子流程（折叠）",
  "Ad-hoc sub-process (expanded)": "临时子流程（展开）",
  "Start event": "开始事件",
  "Message end event": "消息结束事件",
  "Escalation end event": "升级结束事件",
  "Error end event": "错误结束事件",
  "Compensation end event": "补偿结束事件",
  "Signal end event": "信号结束事件",
  "Terminate end event": "终止结束事件",
  "Message intermediate catch event": "消息中间捕获事件",
  "Message intermediate throw event": "消息中间抛出事件",
  "Timer intermediate catch event": "定时中间捕获事件",
  "Escalation intermediate throw event": "升级中间抛出事件",
  "Conditional intermediate catch event": "条件中间捕获事件",
  "Link intermediate catch event": "链接中间捕获事件",
  "Link intermediate throw event": "链接中间抛出事件",
  "Compensation intermediate throw event": "补偿中间抛出事件",
  "Signal intermediate catch event": "信号中间捕获事件",
  "Signal intermediate throw event": "信号中间抛出事件",
  "Connect using association": "使用关联连接",
  "Close minimap": "关闭缩略图",
  "Exclusive gateway": "排他网关",
  "Append receive task": "追加接收任务",
  "Append message intermediate catch event": "追加消息中间捕获事件",
  "Append timer intermediate catch event": "追加定时中间捕获事件",
  "Append conditional intermediate catch event": "追加条件中间捕获事件",
  "Append signal intermediate catch event": "追加信号中间捕获事件",
  "Open {element}": "打开 {element}",
  "Set color": "设置颜色",
  Default: "默认",
  Blue: "蓝色",
  Orange: "橙色",
  Green: "绿色",
  Red: "红色",
  Purple: "紫色",
  Cyan: "青色",
  Yellow: "黄色",
  Gray: "灰色",
  General: "常规",
  Documentation: "文档",
  Compensation: "补偿",
  Error: "错误",
  Link: "链接",
  Message: "消息",
  "Multi-instance": "多实例",
  Completion: "完成",
  Signal: "信号",
  Escalation: "升级",
  Timer: "定时",
  Process: "流程",
  Name: "名称",
  ID: "ID",
  Executable: "可执行",
  "Element documentation": "元素文档",
  "Data Object Reference": "数据对象引用",
  "Data Output Association": "数据输出关联",
  "Conditional flow": "条件流",
  "Default flow": "默认流",
  "Sequence Flow": "顺序流",
  "Expanded Sub Process": "展开子流程",
  "Collapsed Sub Process": "折叠子流程",
  Participant: "参与者",
  "Participant Name": "参与者名称",
  "Participant ID": "参与者 ID",
  "Process ID": "流程 ID",
  "Process name": "流程名称",
  "Process documentation": "流程文档",
  Collaboration: "协作",
  Group: "分组",
  "Empty pool/participant": "空泳池/参与者",
  "Expanded pool/participant": "展开泳池/参与者",
  "Data Store Reference": "数据存储引用",
  "Sub-process": "子流程",
  "Expanded Ad Hoc Sub Process": "展开临时子流程",
  "Completion condition": "完成条件",
  "Cancel remaining instances": "取消剩余实例",
  "Event Sub Process": "事件子流程",
  "Link Intermediate Throw Event": "链接中间抛出事件",
  "Timer Intermediate Catch Event": "定时中间捕获事件",
  Type: "类型",
  "<none>": "<无>",
  Date: "日期",
  Duration: "持续时间",
  Cycle: "周期",
  Value: "值",
  "A cycle defined as ISO 8601 repeating intervals format.":
    "以 ISO 8601 重复间隔格式定义的周期。",
  "every 10 seconds, up to 5 times": "每 10 秒一次，最多 5 次",
  "every day, infinitely": "每天一次，无限重复",
  "Documentation: Timer events": "文档：定时器事件",
  "A time duration defined as ISO 8601 durations format.":
    "以 ISO 8601 持续时间格式定义的时间段。",
  "15 seconds": "15 秒",
  "1 hour and 30 minutes": "1 小时 30 分钟",
  "14 days": "14 天",
  "A specific point in time defined as ISO 8601 combined date and time representation.":
    "以 ISO 8601 日期与时间组合表示法定义的特定时间点。",
  "UTC time": "UTC 时间",
  "UTC plus 2 hours zone offset": "UTC +2 小时时区偏移",
  "Signal Intermediate Catch Event": "信号中间捕获事件",
  "Global signal reference": "全局信号引用",
  "Create new ...": "新建...",
  "Signal End Event": "信号结束事件",
  "Terminate End Event": "终止结束事件",
  "Compensation start event": "补偿开始事件",
  "Compensate End Event": "补偿结束事件",
  "Wait for completion": "等待完成",
  "Activity reference": "活动引用",
  "Error start event": "错误开始事件",
  "Error End Event": "错误结束事件",
  "Global error reference": "全局错误引用",
  "Global message reference": "全局消息引用",
  "Escalation start event": "升级开始事件",
  "Escalation End Event": "升级结束事件",
  "Global escalation reference": "全局升级引用",
  "Complex Gateway": "复杂网关",
  "Align elements left": "左对齐元素",
  "Align elements center": "水平居中对齐元素",
  "Align elements right": "右对齐元素",
  "Align elements top": "顶对齐元素",
  "Align elements middle": "垂直居中对齐元素",
  "Align elements bottom": "底对齐元素",
  "Distribute elements horizontally": "水平分布元素",
  "Distribute elements vertically": "垂直分布元素",
  "Align elements": "对齐元素",
  "Multiple elements are selected. Select a single element to edit its properties.":
    "已选中多个元素。请选择单个元素以编辑其属性。",
  "Collapsed Ad Hoc Sub Process": "折叠临时子流程",
};

const untranslated = new Set();
function customTranslate(
  template: string,
  replacements?: Record<string, string>,
) {
  if (!translations[template]) {
    untranslated.add(template);
    console.log([...untranslated]);
  }
  let text = translations[template] || template;
  if (replacements) {
    Object.keys(replacements).forEach((key) => {
      text = text.replace(new RegExp(`\\{${key}\\}`, "g"), replacements[key]);
    });
  }
  return text;
}

const customTranslateModule = {
  translate: ["value", customTranslate],
};

export default customTranslateModule;
